name: Combine XSD Schema v3.2

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Combine XSD schema into single file
        run: python scripts/combine_xsd_schema.py

      - name: Upload merged XSD as artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-xsd
          path: dist/itop_design_combined.xsd

      - name: Commit combined schema to branch
        if: github.event.pull_request.merged == true
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dist/itop_design_combined.xsd
          git commit -m "Auto-update combined schema after merge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
