name: Validate iTop datamodel XML version 3.2 (xmllint)

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install xmllint (libxml2-utils)
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libxml2-utils

    - name: Verify files exist
      run: |
        test -f 3.2/itop_design.xsd || (echo "XSD file missing!" && exit 1)
        test -f test/datamodel.must-validate.xml || (echo "XML file missing!" && exit 1)

    - name: Validate datamodel.must-validate.xml against itop_design.xsd
      run: |
        xmllint --noout --schema 3.2/itop_design.xsd test/datamodel.must-validate.xml
